server:
  port: 3344
spring:
  application:
    name: springcloud-study-config
  cloud:
    config:
      server:
        git:
          # uri: git@github.com:gongxings/springcloud-study-config.git
          uri: https://github.com/QLoveChen/spring-cloud-study.git
          search-paths: config-repo
          username:   #’À∫≈
          password:   #√‹¬Î