server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  instance:
    instance-id: gateway-9572
    prefer-ip-address: true
  client:
    service-url:
      # 单机版配置defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka #设置与eureka server 交互的地址查询服务和注册服务都需要依赖的地址
      #集群配置
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

info:
  app.name: microservicecloud-zuul-gateway
  company.name: www.oneday.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

#zuul:
#  routes:
#    mydept.serviceId: microservicecloud-dept
#    mydept.path: /mydept/*
#  #多个用"*" ignored-services: "*"
#  ignored-services: microservicecloud-dept
#  #公共前缀
#  prefix: /springcloud