#配置服务器信息
server:
  port: 8003
  #context-path: /study 配置根目录


#数据库信息配置
spring:
  application:
    name: microservicecloud-dept  #应用名称
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?useUnicode=true&&serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #druid连接池配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters,去掉监控界面sql无法统计，‘wall’用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    userGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.oneday.springcloud.micriservicecloudapi.entities
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    cache-enabled: true #开启二级缓存

#客户端注册进eureka服务列表
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    #服务实例名称修改
    instance-id: microservicecloud-dept8003
    #访问路径显示IP地址
    prefer-ip-address: true

info:
  app.name: microservicecloud-micoservices
  company.name: www.oneday.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


